plugins:
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
  - learning-at-ada/ada-languages/readme.md
  - learning-at-ada/internet-searching/readme.md
  - learning-at-ada/problem-solving/readme.md